### ISSUE TITLE
Error in devtools::install_github("sachsmc/pseval")

### ISSUE THREAD

**Issue by peterbriangilbert** [sachsmc/pseval#22]
In Linux, I first did install.packages(devtools)
Then I ran
devtools::install_github("sachsmc/pseval")

I got the following error:
Installing github repo(s) sachsmc/pseval/master from hadley
Installing sachsmc/pseval.zip from https://github.com/hadley/sachsmc/pseval/zipball/master
Error: client error: (404) Not Found

**Comment by sachsmc** [comment]
What version of R are you using?

**Comment by peterbriangilbert** [comment]
I think that’s the issue, I’ll get a more recent version, Peter

**Comment by sachsmc** [comment]
I'm assuming you figured out the problem so I'm going to close this issue.
